#!/usr/bin/env node
/*
 * MCP Guardrail Companion Server — Codex fallback for hooks/*.js
 *
 * Emitted to `.codex-mcp-guard/server.js` in USE templates when
 * `codex_hooks.feature_flag = under_development` (see sync-manifest.yaml
 * cli_variants.hooks/*.js.codex.feature_flag_fallback).
 *
 * Contract: every reject-condition implemented in .claude/hooks/*.js MUST
 * have a coverage-equivalent reject-condition in this server. Enforced by
 * /sync emit-time validator 13 (AST predicate-set match) — see v5 spec.
 *
 * Module system: CommonJS (matches .claude/hooks/*.js convention).
 *
 * Architecture
 * ────────────
 * 1. POLICIES populated from sibling policies.json at import time.
 *    Generated by `extract-policies.mjs --write-policies` and refreshed
 *    on every /sync. Each per-tool array entry is `{ source_file,
 *    cc_matchers, invocation: "subprocess" }` — server.js spawns
 *    `node ../hooks/<source_file>` for every entry on the matching
 *    Codex tool call.
 *
 * 2. POLICIES_POPULATED flips true iff at least one wrapped Codex tool
 *    has ≥1 policy entry. Empty policies.json or absent file ⇒ stays
 *    false; the gate at the bottom of this file then exits 2 with the
 *    refusal message rather than running the server fail-open.
 *
 * 3. On MCP tool invocation:
 *    - Synthesize a CC-shaped PreToolUse JSON payload from the MCP args
 *      ({ tool_name, tool_input, hook_event_name, cwd, session_id }).
 *    - For each policy entry, spawn the hook script as a subprocess
 *      (5s timeout per cc-artifacts.md Rule 7), pipe payload to stdin,
 *      capture stdout + exit code.
 *    - Exit 0 ⇒ allow; exit 2 ⇒ deny with hook stdout's instructAndWait
 *      shape translated to MCP isError; other exits ⇒ allow + log to
 *      violations.jsonl (per zero-tolerance.md Rule 2).
 *    - Every policy entry MUST allow for the call to forward.
 */

"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const HERE = __dirname;

// Layout detection: this server runs in two distinct emission shapes.
//
//   1. loom-dev layout                        — HERE = <repo>/.claude/codex-mcp-guard/
//      hooks at HERE/../hooks                 → COC_ROOT = HERE/..
//
//   2. multi-CLI USE-template / coc-project   — HERE = <repo>/.codex-mcp-guard/
//      hooks at HERE/../.claude/hooks         → COC_ROOT = HERE/../.claude
//
// loom-dev and multi-CLI USE templates additionally place a symlink
// `<root>/.claude/codex-mcp-guard → ../.codex-mcp-guard` (per
// sync-manifest.yaml::multi_cli_overlays.<type>.symlinks); node resolves
// __dirname via fs.realpath so HERE always points to the real directory,
// not the symlink. Both layouts converge on COC_ROOT = `<root>/.claude/`.
function resolveCocRoot(here) {
  const loomDev = path.resolve(here, "..");
  if (fs.existsSync(path.join(loomDev, "hooks"))) return loomDev;
  const useTemplate = path.resolve(here, "..", ".claude");
  if (fs.existsSync(path.join(useTemplate, "hooks"))) return useTemplate;
  // Neither layout matches — fall back so HOOKS_DIR still points
  // somewhere; the startup existence check (logged via self-check
  // diagnostics, line ~305) will surface the failure loudly.
  return loomDev;
}
const COC_ROOT = resolveCocRoot(HERE);
const HOOKS_DIR = path.join(COC_ROOT, "hooks");
const POLICIES_PATH = path.join(HERE, "policies.json");
const VIOLATIONS_PATH = path.join(COC_ROOT, "learning", "violations.jsonl");
const SUBPROCESS_TIMEOUT_MS = 5000; // cc-artifacts.md Rule 7

// Tool-wrap scope (parity with cli_variants.hooks/*.js.codex.wraps).
// Read-path tools (read, grep_tool, glob_tool) are INTENTIONALLY out of
// scope in the MCP fallback path — hooks with read-only policies are
// skipped on Codex when codex_hooks=under_development. Documented in
// README.md § Scope.
const WRAPPED_TOOLS = Object.freeze(["apply_patch", "unified_exec", "shell"]);

// ---------------------------------------------------------------------------
// Policy table — populated from sibling policies.json
// ---------------------------------------------------------------------------
function loadPolicies() {
  const empty = Object.fromEntries(WRAPPED_TOOLS.map((t) => [t, []]));
  if (!fs.existsSync(POLICIES_PATH)) return { policies: empty, source: null };
  try {
    const raw = JSON.parse(fs.readFileSync(POLICIES_PATH, "utf8"));
    const merged = Object.fromEntries(
      WRAPPED_TOOLS.map((t) => [
        t,
        Array.isArray(raw.policies?.[t]) ? raw.policies[t] : [],
      ]),
    );
    return { policies: merged, source: POLICIES_PATH };
  } catch (e) {
    process.stderr.write(
      `codex-mcp-guard: failed to parse ${POLICIES_PATH}: ${e.message}\n`,
    );
    return { policies: empty, source: null };
  }
}

const { policies: POLICIES, source: POLICIES_SOURCE } = loadPolicies();

// POLICIES_POPULATED true iff at least one wrapped tool has at least
// one policy entry. Per zero-tolerance.md Rule 2 (no stubs), an empty
// table is indistinguishable from no enforcement and MUST keep the
// fail-closed gate engaged. Note: this is a derived runtime flag, NOT
// a hand-edited constant — it reflects the actual state of POLICIES.
const POLICIES_POPULATED = WRAPPED_TOOLS.some(
  (t) => Array.isArray(POLICIES[t]) && POLICIES[t].length > 0,
);

// ---------------------------------------------------------------------------
// Violations log helper — writes to .claude/learning/violations.jsonl
// when a policy enforcement decision is non-trivial (subprocess
// timeout, parse error, deny). Best-effort: hooks own the canonical
// violation log; this is supplementary breadcrumbs from the MCP path.
// ---------------------------------------------------------------------------
function logViolation(entry) {
  try {
    const dir = path.dirname(VIOLATIONS_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const line = JSON.stringify({ ts: new Date().toISOString(), ...entry });
    fs.appendFileSync(VIOLATIONS_PATH, line + "\n");
  } catch {
    // Failure to log is non-fatal; do not block tool execution.
  }
}

// ---------------------------------------------------------------------------
// Hook subprocess invocation — exact CC PreToolUse contract
// ---------------------------------------------------------------------------
// Exit code semantics per .claude/hooks/*.js convention:
//   0 = allow, 2 = block, other = warn (treated as allow + logged)
// Synthesizes the CC-shaped stdin payload from MCP args. Each policy
// entry is a separate process; first non-zero, non-2 exit is logged
// but not treated as block (cc-artifacts.md Rule 7 prefers fail-open
// on hook unreliability vs. fail-closed which would block legitimate
// tool calls when a hook script has a bug).
function invokeHook({ hookFile, payload }) {
  const hookPath = path.join(HOOKS_DIR, hookFile);
  if (!fs.existsSync(hookPath)) {
    return {
      verdict: "missing",
      exitCode: -1,
      stdout: "",
      stderr: `hook script not found: ${hookPath}`,
    };
  }
  const r = spawnSync("node", [hookPath], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    timeout: SUBPROCESS_TIMEOUT_MS,
    env: { ...process.env, CLAUDE_PROJECT_DIR: payload.cwd || process.cwd() },
  });
  if (r.error && r.error.code === "ETIMEDOUT") {
    return {
      verdict: "timeout",
      exitCode: -2,
      stdout: r.stdout || "",
      stderr: r.stderr || "",
    };
  }
  if (r.error) {
    return {
      verdict: "error",
      exitCode: -3,
      stdout: r.stdout || "",
      stderr: String(r.error),
    };
  }
  const code = r.status === null ? -4 : r.status;
  let verdict;
  if (code === 0) verdict = "allow";
  else if (code === 2) verdict = "deny";
  else verdict = "warn";
  return {
    verdict,
    exitCode: code,
    stdout: r.stdout || "",
    stderr: r.stderr || "",
  };
}

// ---------------------------------------------------------------------------
// Hook stdout → MCP isError translation
// ---------------------------------------------------------------------------
// CC hooks emit canonical instructAndWait JSON on stdout when blocking.
// Shape: { continue: false, hookSpecificOutput: { hookEventName,
// validation } } (PreToolUse) or { continue: true, systemMessage }
// (Stop-class). MCP requires { isError: true, content: [{ type: "text",
// text }] }. translateDeny extracts the human-readable validation text.
function translateDeny({ hookFile, hookStdout, hookStderr }) {
  let validation = null;
  let continueFlag = null;
  try {
    // Hook may emit multi-line JSON; take the LAST non-empty line that
    // parses as an object. The stdin handler in lib/instruct-and-wait.js
    // emits a single JSON line followed by exit; multi-line output
    // implies bad authoring but we tolerate it gracefully.
    const lines = hookStdout
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    for (let i = lines.length - 1; i >= 0; i--) {
      try {
        const obj = JSON.parse(lines[i]);
        validation =
          obj?.hookSpecificOutput?.validation || obj?.systemMessage || null;
        continueFlag = obj?.continue;
        if (validation) break;
      } catch {
        // not JSON; continue
      }
    }
  } catch {
    /* parse failure — fall through to fallback */
  }
  const text =
    validation ||
    `codex-mcp-guard: hook ${hookFile} blocked the tool invocation` +
      (hookStderr ? `\n\nstderr: ${hookStderr.slice(0, 400)}` : "");
  return {
    isError: true,
    content: [{ type: "text", text }],
    _meta: {
      hook: hookFile,
      continue: continueFlag,
    },
  };
}

// ---------------------------------------------------------------------------
// Policy execution — the load-bearing function
// ---------------------------------------------------------------------------
// Runs every policy registered for `tool` against `input`. Returns
// either { allow: true } or { allow: false, mcpResponse: <isError> }.
// First deny short-circuits remaining policies (the same as CC's hook
// chain semantics — first hook to exit 2 blocks the tool call).
function evaluatePolicies({ tool, input, session_id, cwd }) {
  const list = POLICIES[tool] || [];
  if (list.length === 0) {
    // No policies for this tool — but POLICIES_POPULATED gate above
    // guarantees at least one wrapped tool has policies. Empty per-
    // tool array means "no enforcement on this specific tool"; the
    // call forwards (allow). This matches CC behavior where a tool
    // matcher with zero hooks does not block the call.
    return { allow: true, decisions: [] };
  }
  const decisions = [];
  for (const policy of list) {
    const payload = {
      hook_event_name: "PreToolUse",
      tool_name: tool,
      tool_input: input,
      session_id: session_id || null,
      cwd: cwd || process.cwd(),
    };
    const result = invokeHook({ hookFile: policy.source_file, payload });
    decisions.push({ source_file: policy.source_file, ...result });
    if (result.verdict === "deny") {
      const mcpResponse = translateDeny({
        hookFile: policy.source_file,
        hookStdout: result.stdout,
        hookStderr: result.stderr,
      });
      logViolation({
        kind: "codex_mcp_guard_deny",
        tool,
        source_file: policy.source_file,
        cwd: payload.cwd,
      });
      return { allow: false, mcpResponse, decisions };
    }
    if (result.verdict === "timeout") {
      // Per cc-artifacts.md Rule 7 — timeout falls open + logs.
      logViolation({
        kind: "codex_mcp_guard_timeout",
        tool,
        source_file: policy.source_file,
        timeout_ms: SUBPROCESS_TIMEOUT_MS,
      });
    } else if (
      result.verdict === "warn" ||
      result.verdict === "error" ||
      result.verdict === "missing"
    ) {
      // Non-blocking deviations are logged and the call still
      // proceeds — the alternative (fail-closed on any hook bug)
      // would deny every Codex call when one of N hooks regresses.
      logViolation({
        kind: "codex_mcp_guard_" + result.verdict,
        tool,
        source_file: policy.source_file,
        exit_code: result.exitCode,
      });
    }
  }
  return { allow: true, decisions };
}

// ---------------------------------------------------------------------------
// Self-check — design per task spec acceptance criteria
// ---------------------------------------------------------------------------
function selfCheck() {
  const lines = [];
  lines.push(`POLICIES_POPULATED=${POLICIES_POPULATED}`);
  lines.push(`POLICIES_SOURCE=${POLICIES_SOURCE || "(none)"}`);
  for (const t of WRAPPED_TOOLS) {
    const list = POLICIES[t] || [];
    lines.push(
      `tool=${t} entries=${list.length} files=[${list.map((e) => e.source_file).join(",")}]`,
    );
  }
  lines.push(
    `HOOKS_DIR=${HOOKS_DIR} hooks_dir_exists=${fs.existsSync(HOOKS_DIR)}`,
  );
  lines.push(`SUBPROCESS_TIMEOUT_MS=${SUBPROCESS_TIMEOUT_MS}`);
  process.stdout.write(lines.join("\n") + "\n");
  process.exit(POLICIES_POPULATED ? 0 : 2);
}

// ---------------------------------------------------------------------------
// Smoke check — run a synthetic tool call through evaluatePolicies and
// print the verdict. Used by the test harness; exposed via CLI flag.
// Usage: node server.js --smoke <tool> <json-tool-input>
// ---------------------------------------------------------------------------
function smokeCheck(tool, toolInputJson) {
  if (!WRAPPED_TOOLS.includes(tool)) {
    process.stderr.write(
      `--smoke: tool must be one of ${WRAPPED_TOOLS.join(",")}; got '${tool}'\n`,
    );
    process.exit(2);
  }
  let input;
  try {
    input = JSON.parse(toolInputJson);
  } catch (e) {
    process.stderr.write(`--smoke: invalid JSON tool_input: ${e.message}\n`);
    process.exit(2);
  }
  const result = evaluatePolicies({ tool, input, cwd: process.cwd() });
  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
  process.exit(result.allow ? 0 : 1);
}

// ---------------------------------------------------------------------------
// Structural feature-flag gate — prevents fail-open default
// ---------------------------------------------------------------------------
// Zero-tolerance Rule 2 requires no stubs in production code paths. The
// POLICIES table is populated by /sync from extract-policies.mjs at
// emit time. If POLICIES_POPULATED is false here, the policies.json
// either does not exist or has empty per-tool arrays — running the
// server in that state would fail-open on every tool invocation,
// which is worse than no guardrail at all. Refuse to start.
function refuseUnpopulated() {
  process.stderr.write(
    [
      "codex-mcp-guard: refusing to start with unpopulated POLICIES table.",
      "",
      "policies.json is missing or has no per-tool entries. Running the",
      "server in this state would fail-open on every tool invocation,",
      "which is worse than no guardrail at all (zero-tolerance Rule 2).",
      "",
      "To populate:",
      "  1. Ensure .claude/hooks/*.js contains the production hook policies.",
      "  2. node .codex-mcp-guard/extract-policies.mjs <hook-dir> \\",
      "       --write-policies .codex-mcp-guard/policies.json",
      "  3. Re-run this server.",
      "",
      "See .codex-mcp-guard/README.md § Authoring.",
      "",
    ].join("\n"),
  );
  process.exit(2);
}

// ---------------------------------------------------------------------------
// MCP server entry — lazy-loads @modelcontextprotocol/sdk only when
// actually serving stdio. Keeps the module importable / testable in
// repos where the SDK is not installed (CI on the loom side).
// ---------------------------------------------------------------------------
async function serveStdio() {
  // Lazy-loaded so the test harness + self-check can run without the
  // MCP SDK npm dependency installed in the host repo. The USE
  // template's package.json declares the dep at install time.
  let McpServer, StdioServerTransport, z;
  try {
    ({ McpServer } = require("@modelcontextprotocol/sdk/server/mcp.js"));
    ({
      StdioServerTransport,
    } = require("@modelcontextprotocol/sdk/server/stdio.js"));
    ({ z } = require("zod"));
  } catch (e) {
    process.stderr.write(
      `codex-mcp-guard: @modelcontextprotocol/sdk not installed (${e.message}).\n` +
        "Install via the USE template's package.json before running stdio mode.\n",
    );
    process.exit(2);
  }

  const server = new McpServer(
    { name: "codex-mcp-guard", version: "0.2.0" },
    { capabilities: { tools: {} } },
  );

  const inputShape = {
    input: z.record(z.string(), z.unknown()),
    session_id: z.string().optional(),
    cwd: z.string().optional(),
  };

  for (const tool of WRAPPED_TOOLS) {
    server.registerTool(
      tool,
      {
        description: `Guardrail wrapper for Codex ${tool} — enforces hooks/*.js parity`,
        inputSchema: inputShape,
      },
      async ({ input, session_id, cwd }) => {
        const result = evaluatePolicies({ tool, input, session_id, cwd });
        if (!result.allow) return result.mcpResponse;
        return { content: [{ type: "text", text: "permit" }] };
      },
    );
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// ---------------------------------------------------------------------------
// CLI dispatch
// ---------------------------------------------------------------------------
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args[0] === "--self-check") {
    selfCheck();
  } else if (args[0] === "--smoke") {
    if (args.length < 3) {
      process.stderr.write(
        "usage: server.js --smoke <tool> <json-tool-input>\n",
      );
      process.exit(2);
    }
    if (!POLICIES_POPULATED) refuseUnpopulated();
    smokeCheck(args[1], args[2]);
  } else {
    if (!POLICIES_POPULATED) refuseUnpopulated();
    serveStdio().catch((err) => {
      process.stderr.write(`codex-mcp-guard fatal: ${err.message}\n`);
      process.exit(1);
    });
  }
}

module.exports = {
  POLICIES,
  POLICIES_POPULATED,
  POLICIES_SOURCE,
  WRAPPED_TOOLS,
  SUBPROCESS_TIMEOUT_MS,
  evaluatePolicies,
  invokeHook,
  translateDeny,
  loadPolicies,
};
